name: Quarkus Internal Builds auto-commit
on:
  repository_dispatch:
    types: [trigger-internal]
env:
  LANG: en_US.UTF-8
jobs:
  internal-builds:
    runs-on: ubuntu-latest
    name: "Deploy internal builds"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'internal'
      - name: Edit internal-build-version.txt
        run: |
          echo "${{ github.event.client_payload.build_version }}" > internal-build-version.txt
      - name: Commit and push
        uses: EndBug/add-and-commit@v4
        with:
          author_name: CI
          author_email: andy.damevin+ghaction@redhat.com
          add: 'internal-build-version.txt'
          message: 'Quarkus Internal auto-commit for build: ${{ github.event.client_payload.build_version }}'
          ref: 'internal'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
